
# Configuration File

[local]
copy_config  = true
config_title = ".commands"


#- Default Configs ---------------------------------------------------------------------------------

[init]
license    = "GPLv2"
git_init   = true
git_message= "init: project"
git_ignore = [ "**/.DS_Store", "**/todo", "" ]

[dev]
cd_root    = true


#---------------------------------------------------------------------------------------------------
#- ESP23 Config ------------------------------------------------------------------------------------

[init.esp]
command     = ""
directories = [ "main/include" ]
templates   = [
    { title = "debugs/esp.h", destination = "main/include/debug.h" },
]
git_ignore  = [ ".cache/", "build/", "managed_components/", "", "sdkconfig.old",  ]


[dev.esp]
build = ". %SCRIPT% esp-idf/export.sh > /dev/null && idf.py build"
run   = ". %SCRIPT% esp-idf/export.sh > /dev/null && idf.py flash"
clean = ". %SCRIPT% esp-idf/export.sh > /dev/null && idf.py fullclean"
debug = ". %SCRIPT% esp-idf/export.sh > /dev/null && idf.py menuconfig"
test  = "smonitor /dev/cu.usbmodem1101"


#- C Config ----------------------------------------------------------------------------------------

[init.c]
command     = "%SCRIPT% cmakegenerate.sh %PROJECT_NAME% c"
directories = [ "src", "include", "build", "lib" ]
templates   = [
    { title = "main.c", destination = "src/main.c" },
    { title = "debugs/c.h", destination = "include/debug.h" },
]
git_ignore  = [ ".cache/", "build/", "obj/" ]


[dev.c]
build = "cmake -S . -B build && cmake --build build"
run   = "./bin"
clean = "cd build && rm -rf ./* && cmake .. && make; cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON .."
debug = "lldb"


#- C++ Config --------------------------------------------------------------------------------------

[init.cpp]
command     = "%SCRIPT% cmakegenerate.sh %PROJECT_NAME% cpp"
directories = [ "src", "include", "build", "lib" ]
templates   = [
    { title = "main.cpp", destination = "src/main.cpp" },
    { title = "debugs/cpp.h", destination = "include/debug.h" },
]
git_ignore  = [ ".cache/", "build/", "obj/" ]


[dev.cpp]
build = "cmake -S . -B build && cmake --build build"
run   = "./bin"
clean = "cd build && rm -rf ./* && cmake .. && make; cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON .."
debug = "lldb"


#- Python Config -----------------------------------------------------------------------------------

[init.py]
command     = "python3 -m venv ./.pyenv"
files       = [ "requirements.txt", "tests.py" ]
directories = [ "scripts" ]
templates   = [
    { title = "main.py",  destination = "main.py" },
]
git_ignore  = [ ".pyenv/", "__pycache__/" ]


[dev.py]
run   = "python3 main.py"
test  = "python3 tests.py"
clean = "rm -rf __pycache__/"


#- Go Config ---------------------------------------------------------------------------------------

[init.go]
command     = "go mod init \"github.com/karshPrime/%PROJECT_NAME%\"; go mod tidy"
directories = [ "cmd" ]
templates   = [
    { title = "main.go", destination = "main.go" },
    { title = "debugs/go-logs", destination = "logs/" },
]
git_ignore  = [ "go.sum", "go.mod", "%PROJECT_NAME%" ]


[dev.go]
build = "go build ."
run   = "go run ."
clean = "go clean"
test  = "go test"

#---------------------------------------------------------------------------------------------------

